defmodule AgenticRuntime.Agents.Factory do
  @moduledoc """
  Factory for creating agents with consistent configuration.

  This module centralizes agent creation, ensuring all agents use the same
  middleware stack and base configuration. The Coordinator calls
  `create_agent/1` when starting a conversation session.

  Unlike the host-app scaffolding generated by `mix sagents.setup`, this
  library version accepts the model configuration, system prompt, tools, and
  fallback settings as required options so the calling app retains full control.

  ## Filesystem Scoping

  The FileSystem middleware supports flexible scoping:

  - `{:user, user_id}` — files persist across all conversations for the same user
  - `{:project, project_id}` — files shared within a project
  - `nil` — defaults to `{:agent, agent_id}` (isolated per conversation)
  - Custom tuples like `{:team, team_id}` are also supported
  """

  alias LangChain.ChatModels.ChatAnthropic
  alias LangChain.ChatModels.ChatGoogleAI
  alias LangChain.ChatModels.ChatOpenAI
  alias Sagents.Agent
  alias Sagents.Middleware.ConversationTitle
  # DISABLED (plan: valiant-twirling-crown): HITL middleware removed from stack
  # alias Sagents.Middleware.HumanInTheLoop

  @doc """
  Creates an agent with the standard configuration.

  ## Options

  - `:agent_id` (required) — Unique identifier for this agent.
  - `:model_config` (required) — Primary chat model config (LangChain ChatModel struct).
  - `:base_system_prompt` (required) — Base system prompt string.
  - `:filesystem_scope` — Optional filesystem scope tuple. Defaults to `nil`.
  - `:title_model_config` — Chat model used for title generation. Defaults to `:model_config`.
  - `:tools` — Custom tools (in addition to those provided by middleware). Defaults to `[]`.
  - `:fallback_models` — List of fallback chat models. Defaults to `[]`.
  - `:before_fallback` — Optional `(LLMChain.t -> LLMChain.t)` modifier. Defaults to `nil`.
  - `:interrupt_on` — Map of tool names requiring HITL approval. Pass `nil` to disable.
  - `:scope` — Integrator-defined scope struct (see `AgenticRuntime.Scope`).
    Sagents propagates it as the first positional argument to persistence
    callbacks and to tool `context.scope`. `nil` is allowed for tests, admin
    scripts, or background jobs without a tenant context.
  - `:tool_context` — Map of caller-supplied data passed to tool functions
    via `LLMChain.custom_context`. Defaults to `%{}`.
  """
  def create_agent(opts \\ []) do
    agent_id = Keyword.fetch!(opts, :agent_id)
    main_model_config = Keyword.fetch!(opts, :model_config)
    base_system_prompt = Keyword.fetch!(opts, :base_system_prompt)
    # DISABLED (plan: valiant-twirling-crown): FileSystem middleware removed; opt accepted-but-ignored
    filesystem_scope = Keyword.get(opts, :filesystem_scope, nil)
    title_model_config = Keyword.get(opts, :title_model_config, main_model_config)
    tools = Keyword.get(opts, :tools, [])
    fallback_models = Keyword.get(opts, :fallback_models, [])
    before_fallback = Keyword.get(opts, :before_fallback, nil)
    # DISABLED (plan: valiant-twirling-crown): HITL middleware removed; opt accepted-but-ignored
    interrupt_on = Keyword.get(opts, :interrupt_on, default_interrupt_on())
    scope = Keyword.get(opts, :scope)
    tool_context = Keyword.get(opts, :tool_context, %{})

    Agent.new(
      %{
        agent_id: agent_id,
        model: main_model_config,
        base_system_prompt: base_system_prompt,
        middleware: build_middleware(filesystem_scope, interrupt_on, title_model_config),
        fallback_models: fallback_models,
        before_fallback: before_fallback,
        tools: tools,
        tool_context: tool_context,
        scope: scope
      },
      # Since we specify the full middleware stack, don't add defaults
      replace_default_middleware: true
    )
  end

  # ---------------------------------------------------------------------------
  # Model Configuration Helpers
  # ---------------------------------------------------------------------------

  def build_anthropic_model_config(model_name, api_key, opts \\ []) do
    thinking_opts = Keyword.get(opts, :thinking, %{type: "enabled"})

    ChatAnthropic.new!(%{
      model: model_name,
      api_key: api_key,
      stream: true,
      thinking: thinking_opts
    })
  end

  def build_openai_model_config(model_name, api_key) do
    ChatOpenAI.new!(%{
      model: model_name,
      api_key: api_key,
      stream: true
    })
  end

  def build_googleai_model_config(model_name, api_key) do
    ChatGoogleAI.new!(%{
      model: model_name,
      api_key: api_key,
      stream: true
    })
  end

  # ---------------------------------------------------------------------------
  # Human-in-the-Loop Configuration
  # ---------------------------------------------------------------------------

  defp default_interrupt_on, do: nil

  # ---------------------------------------------------------------------------
  # Middleware Configuration
  # ---------------------------------------------------------------------------

  # Build the middleware stack matching `Sagents.Agent.build_default_middleware/3`:
  #   1. TodoList — Task management with write_todos tool
  #   2. ConversationTitle — Auto-generate titles (async, positioned early)
  #   3. FileSystem — Virtual filesystem (ls, read_file, write_file, etc.)
  #   4. SubAgent — Delegate to specialized child agents
  #   5. Summarization — Compress long conversations
  #   6. PatchToolCalls — Fix dangling tool calls from interrupted conversations
  #   7. AskUserQuestion — Structured questions with typed responses
  #
  # HumanInTheLoop is conditionally appended last so it can dispatch to
  # interrupt-producing middleware that ran earlier.
  defp build_middleware(_filesystem_scope, _interrupt_on, title_model_config) do
    [
      Sagents.Middleware.TodoList,
      {ConversationTitle,
       [
         chat_model: title_model_config,
         fallbacks: []
       ]},
      # DISABLED (plan: valiant-twirling-crown): FileSystem middleware
      # {Sagents.Middleware.FileSystem, [filesystem_scope: _filesystem_scope]},
      {Sagents.Middleware.SubAgent,
       [
         block_middleware: [
           Sagents.Middleware.Summarization,
           Sagents.Middleware.ConversationTitle
           # DISABLED (plan: valiant-twirling-crown): AskUserQuestion in SubAgent block_middleware
           # Sagents.Middleware.AskUserQuestion
         ]
       ]},
      Sagents.Middleware.Summarization,
      Sagents.Middleware.PatchToolCalls
      # DISABLED (plan: valiant-twirling-crown): AskUserQuestion middleware
      # Sagents.Middleware.AskUserQuestion
    ]

    # DISABLED (plan: valiant-twirling-crown): HumanInTheLoop append
    # |> HumanInTheLoop.maybe_append(_interrupt_on)
  end
end
