# SPDX-FileCopyrightText: SUSE LLC
# SPDX-License-Identifier: Apache-2.0

name: Continuous Integration

on:
  push:
    branches:
      - main
    paths-ignore:
      - "VERSION"
      - "CHANGELOG.md"
  pull_request:
    types: [opened, synchronize, labeled]
    paths-ignore:
      - "VERSION"
  workflow_dispatch:
  workflow_call:
  repository_dispatch:
    types: [start-ci, deploy-demo]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  license-headers:
    name: Ensure license headers are present and correct
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
        with:
          fetch-depth: 0
      - name: Check license Headers
        uses: apache/skywalking-eyes/header@61275cc80d0798a405cb070f7d3a8aaf7cf2c2c1 # v0.8.0
